language: go
go:
- 1.7
git:
  depth: 9999999
env:
  global:
  - secure: r8sXH4GiNtvSJAZH0lEVhMNE1gy21sKATaEwGRXLcHIPOyzjJvEg82ft/8Tj1ji+hPBtYyMTS2ULdlHVGuFfy0LfRgWE0tntp/zFMYv8mLIT79jYC1dyHL6RDb1gKYwcXI0+nxh4JTnUkOQtkKbY9mteUDXKSSI2DH3HEzRFcFN3/or5H/KmZZTKFHukUb0xgMFw+GAE/y+nxwlU4SStci4Wnuh2sctErENdXj7MKtz1jYYnMLbly5T2+RbyNFn9jjvncbBWaGBDug1UxEf5f1jBABTpcpHLowoLl6hngGvpDKCcyInX99rEd6n4JjCj3CqYnHAAzhhyAgSCep0wwsWysEEaavyuzX8L80mNQ6PAedJukW1uXL5PeDjzdFsvzRUxqy9dY7ZduEilsRomd54QFY5F2Q7i57Tz64g8jNHwjSfj+RuwlYf6IHNQKAtMP0EMT7EUj0lo5og3BUxltHtb09nspQb+oITSyjjXXK65VDtsgF2+4L3HIjwDuzJFsfGN1Faa1bwj3CxTN8oR7C5jdEXLJaKMvL1u8NVTXa9z9LrGrzhSSe9ZtmV97dnSbQqIEPyXEuy5UlyordkUrEuyQHrpSu32hPgQgv0ocLfZdOJEAs16X2A6v6pm45A79P4nJiEgZT0lbKYBkfvH4leCmPFiQ+AAsJyUHEFu2h0=
  - secure: KmQ34SA6fW8E/PiqryZVqSb0khuPUeAUWwGKaf5z9zewMYvAxCiBQuu61gBbUZnUPv9IhrHntW0p9CCTBdeLpoS9ogc32etvOJak8vnk+PYp7o97022F26T2mglcmR4C4scoOc3iNUyRrz3Ik7N0ffnVFEYueZPBVV2pDf3UyjxfQRqGSIF04TOJroG6Rmi2m/KahiobmhVpGemmYMOuFAm4howIc3GqY3u5twEeHUU/ywlFKJvOy3bZXliI0/Oci5X5ge2MTGpgX/BrUFIICH4rn0cj2DBUpsoE0GcV2b5EjYaBgYdG94I9rbpx0/owdYsPMjEFjkNiv7fgonsMQ9UXHPwOAxs/D1qIRQbUMTwrYD373rTwBLyg7ip0//Wthxjwmw/6Gf9TyZg9vL3lOpLDYlLDKyiGdfJ9f68CxFvLvAGGqDf0PoXcn3HEVFxY5oQAA0pNhGBK0nehrvKFM2yXDI1uVongxeYoyj99nWuG374E3rWICiI+oPy2sP64UrRUn5f0MpDLytB9CIrqg2RJD0yRfedDOHl/qZGF7TDhVFqBEmbRHNbtJCAdej/mg7PmtIR7NycwjE35uoPGX8MVX3FNFUeFtREribNXERL5T/IOReAvULWMEiScS3bZhKAmym1Nyb1FRcMEzAwK8GPrVAbMZX9Z/shml/sc6gQ=
  - secure: cy7ahWK5ebgBRzuFUpmiZurKLBN3eAf3M96sL82JUdGXP6thGjcvqalVo5vGqWstRgGVEoapfTgMW2BPxwpzl/9ra4UoDKKO0WdYYhxX3rPQ8ZfT/qo7UGHbbaJL6RCNY6sPS4mHRNnOCtwRSxFg5elq3m2XsbU/j7EJo58YS/8HTsMhB/7tnRdfjoKFEjOh1j1EPEebNhIETtynEMPjppv9SOspPiQ6uPDjH0Mjn4N3A/R9AROfzuhEkp5PzsjWCDNd9H3+lg/tSRPcRnO3bhKURIER1B1dxUv/21/hDCUNlGYt1JD5OmIQDD2v3VW/axDkMvdMTbkb33zfoEvkE9+m1kgWF4Zc0y83RwNO6+oKkdmI48eu1GjkwpoZ5wUnD9zMLsWeRnrPFMssfmK1xwlvakYfC+N67afo8KtYvTKe98PIV2TRY+H0S+9voPKA+qjHzoFDHvEkINRLXF/fMu3i3g9TlcYzziZsFglkTBxXj/vDYnfgWrtDEVkb/Rs3KP4w2/S+GOEcJ0DdKmkG6HyyIhirEHC7XBIY30A5mY774+WQqVOtS5W/zTrCS3uAXvjUiEl6uf7M2qWiCnC8v5E9vJZoZqaAHyPJttqFWw2Uqx84TYBKHLIEleVus4n1x4WenvJwuM1B5ynTgyftHQ/Dby0UezPQVD7qokHtuLg=
install:
- make get-deps
script:
- make test
- make cross-build
deploy:
- provider: script
  script: make deploy
  skip_cleanup: true
  on:
    repo: getcarina/carina
    tags: true
